export const Breadcrumb = {
  home: { label: "Beranda", value: "/" },
  arsip: { label: "Arsip", value: "/arsip" },
  atph: { label: "ATPH", value: "/atph" },
  daftarHadir: { label: "Daftar Hadir", value: "/daftar-hadir" },
  daftarPelanggaran: {
    label: "Daftar Pelanggaran",
    value: "/daftar-pelanggaran",
  },
  dpib: { label: "DPIB", value: "/dpib" },
  galeri: { label: "Galeri", value: "/galeri" },
  kalenderAkademik: { label: "Kalender Akademik", value: "/kalender-akademik" },
  petaSitusKontak: {
    label: "Peta Situs & Kontak",
    value: "/peta-situs-kontak",
  },
  portalBerita: { label: "Portal Berita", value: "/portal-berita" },
  saranaPrasarana: { label: "Sarana & Prasarana", value: "/sarana-prasarana" },
  sejarah: { label: "Sejarah", value: "/sejarah" },
  siswa: { label: "Siswa", value: "/siswa" },
  strukturOrganisasi: {
    label: "Struktur Organisasi",
    value: "/struktur-organisasi",
  },
  tataTertib: { label: "Tata Tertib", value: "/tata-tertib" },
  tenagaKependidikan: {
    label: "Tenaga Kependidikan",
    value: "/tenaga-kependidikan",
  },
  tenagaPendidik: { label: "Tenaga Pendidik", value: "/tenaga-pendidik" },
  tbsm: { label: "TBSM", value: "/tbsm" },
  tkj: { label: "TKJ", value: "/tkj" },
  trko: { label: "TRKO", value: "/trko" },
  visiMisi: { label: "Visi - Misi", value: "/visi-misi" },
};
