export const urls = {
  ARSIP: "/arsip",
  DAFTAR_HADIR: "/daftar-hadir",
  DAFTAR_PELANGGARAN: "/daftar-pelanggaran",
  DASHBOARD: "/dashboard",
  GALERI: "/galeri",
  HOME: "/",
  JURUSAN: "/jurusan",
  KALENDER_AKADEMIK: "/kalender-akademik",
  LOGIN: "/login",
  PETA_SITUS_KONTAK: "/peta-situs-kontak",
  PORTAL_BERITA: "/portal-berita",
  SARANA_PRASARANA: "/sarana-prasarana",
  SEJARAH: "/sejarah",
  SISWA: "/siswa",
  STRUKTUR_ORGANISASI: "/struktur-organisasi",
  TATA_TERTIB: "/tata-tertib",
  TENAGA_KEPENDIDIKAN: "/tenaga-kependidikan",
  TENAGA_PENDIDIK: "/tenaga-pendidik",
  VISI_MISI: "/visi-misi",
};
