import WidgetProvider from "@/context";
import "./global.scss";

export const metadata = {
  title: "Idong Project",
  description: "Generated by Muhammad Jaury",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <WidgetProvider>
        <body>{children}</body>
      </WidgetProvider>
    </html>
  );
}
