import WidgetProvider from "@/context";
import Providers from "@/redux/Provider";
import "./global.scss";

export const metadata = {
  title: "Idong Project",
  description: "Generated by Muhammad Jaury",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta
        httpEquiv="Content-Security-Policy"
        content="upgrade-insecure-requests"
      />
      <body>
        <Providers>
          <WidgetProvider>{children}</WidgetProvider>
        </Providers>
      </body>
    </html>
  );
}
